### ISSUE TITLE
Activation not possible

### ISSUE THREAD

**Issue by thorsten** [nicolasbarbe/magnolia-vagrant#1]
Thanks for this piece of code!

Everything's just fine, except the activation:

```
author_1 | 2015-04-28 13:02:44,725 ERROR info.magnolia.module.activation.ExchangeTask      : Failed to deactivate content.
author_1 | info.magnolia.cms.exchange.ExchangeException: Not able to send the activation request [http://localhost:8080/magnoliaPublic/.magnolia/activation]: cannot retry due to server authentication, in streaming mode
author_1 |  at info.magnolia.module.activation.BaseSyndicatorImpl.activate(BaseSyndicatorImpl.java:443)
author_1 |  at info.magnolia.module.activation.SimpleSyndicator$2.runTask(SimpleSyndicator.java:132)
author_1 |  at info.magnolia.module.activation.ExchangeTask.run(ExchangeTask.java:75)
author_1 |  at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
author_1 |  at java.lang.Thread.run(Thread.java:745)
author_1 | Caused by: java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
author_1 |  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1426)
author_1 |  at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2691)
author_1 |  at info.magnolia.module.activation.BaseSyndicatorImpl.transportActivatedData(BaseSyndicatorImpl.java:482)
author_1 |  at info.magnolia.module.activation.BaseSyndicatorImpl.activate(BaseSyndicatorImpl.java:407)
author_1 |  ... 4 more
author_1 | 2015-04-28 13:02:44,736 ERROR info.magnolia.module.activation.SimpleSyndicator  : Not able to send the activation request [http://localhost:8080/magnoliaPublic/.magnolia/activation]: cannot retry due to server authentication, in streaming mode
author_1 | info.magnolia.cms.exchange.ExchangeException: Not able to send the activation request [http://localhost:8080/magnoliaPublic/.magnolia/activation]: cannot retry due to server authentication, in streaming mode
author_1 |  at info.magnolia.module.activation.BaseSyndicatorImpl.activate(BaseSyndicatorImpl.java:443)
author_1 |  at info.magnolia.module.activation.SimpleSyndicator$2.runTask(SimpleSyndicator.java:132)
author_1 |  at info.magnolia.module.activation.ExchangeTask.run(ExchangeTask.java:75)
author_1 |  at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
author_1 |  at java.lang.Thread.run(Thread.java:745)
author_1 | Caused by: java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
author_1 |  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1426)
author_1 |  at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2691)
author_1 |  at info.magnolia.module.activation.BaseSyndicatorImpl.transportActivatedData(BaseSyndicatorImpl.java:482)
author_1 |  at info.magnolia.module.activation.BaseSyndicatorImpl.activate(BaseSyndicatorImpl.java:407)
author_1 |  ... 4 more
```

**Comment by nicolasbarbe** [comment]
Good point, I have not changed the default configuration for the subscribers. The author instance should point to localhost:80, not localhost:8080.

**Comment by thorsten** [comment]
Changing the value to localhost:80 in the configuration doesn't work either.

**Comment by nicolasbarbe** [comment]
Right, it has to be the Vagrant VM IP which is 10.1.2.3. Another approach is to create a link between both containers. 

I will have a look at the later approach to see if I can automate this in Magnolia.
